<?php

namespace Database\Seeders;

use App\Models\Category;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [
                'product_type_id' => 1,
                'parent_id' => null,
                'name' => 'AI Productivity Tools',
                'logo' => null,
                'description' => null,
                'tools_count' => 0,
                'status' => 'Active',
                'sort_order' => null,
            ],
            [
                'product_type_id' => 1,
                'parent_id' => 1,
                'name' => 'Email',
                'logo' => 'email',
                'description' => null,
                'tools_count' => 0,
                'status' => 'Active',
                'sort_order' => null,
            ],
            [
                'product_type_id' => 1,
                'parent_id' => 1,
                'name' => 'Education / Studies',
                'logo' => null,
                'description' => null,
                'tools_count' => 0,
                'status' => 'Active',
                'sort_order' => null,
            ],
            [
                'product_type_id' => 1,
                'parent_id' => 1,
                'name' => 'Extensions ChatGPT',
                'logo' => null,
                'description' => null,
                'tools_count' => 0,
                'status' => 'Active',
                'sort_order' => null,
            ],
            [
                'product_type_id' => 1,
                'parent_id' => 1,
                'name' => 'Files & Spreadsheets',
                'logo' => null,
                'description' => null,
                'tools_count' => 0,
                'status' => 'Active',
                'sort_order' => null,
            ],
            [
                'product_type_id' => 1,
                'parent_id' => 1,
                'name' => 'Memory',
                'logo' => null,
                'description' => null,
                'tools_count' => 0,
                'status' => 'Active',
                'sort_order' => null,
            ],
            [
                'product_type_id' => 1,
                'parent_id' => 1,
                'name' => 'Search engine',
                'logo' => null,
                'description' => null,
                'tools_count' => 0,
                'status' => 'Active',
                'sort_order' => null,
            ],
            [
                'product_type_id' => 1,
                'parent_id' => 1,
                'name' => 'Presentation',
                'logo' => null,
                'description' => null,
                'tools_count' => 0,
                'status' => 'Active',
                'sort_order' => null,
            ],
            [
                'product_type_id' => 1,
                'parent_id' => 1,
                'name' => 'Productivity',
                'logo' => null,
                'description' => null,
                'tools_count' => 0,
                'status' => 'Active',
                'sort_order' => null,
            ],
            [
                'product_type_id' => 1,
                'parent_id' => 1,
                'name' => 'Translation',
                'logo' => null,
                'description' => null,
                'tools_count' => 0,
                'status' => 'Active',
                'sort_order' => null,
            ],
            [
                'product_type_id' => 1,
                'parent_id' => null,
                'name' => 'AI Assistants',
                'logo' => null,
                'description' => null,
                'tools_count' => 0,
                'status' => 'Active',
                'sort_order' => null,
            ],
            [
                'product_type_id' => 1,
                'parent_id' => 11,
                'name' => 'Legal Assistants',
                'logo' => null,
                'description' => null,
                'tools_count' => 0,
                'status' => 'Active',
                'sort_order' => null,
            ],
            [
                'product_type_id' => 1,
                'parent_id' => 11,
                'name' => 'Life Assistants',
                'logo' => null,
                'description' => null,
                'tools_count' => 0,
                'status' => 'Active',
                'sort_order' => null,
            ],
            [
                'product_type_id' => 1,
                'parent_id' => 11,
                'name' => 'AI Chat & Assistant',
                'logo' => null,
                'description' => null,
                'tools_count' => 0,
                'status' => 'Active',
                'sort_order' => null,
            ],
            [
                'product_type_id' => 1,
                'parent_id' => 11,
                'name' => 'ChatBots',
                'logo' => null,
                'description' => null,
                'tools_count' => 0,
                'status' => 'Active',
                'sort_order' => null,
            ],
            [
                'product_type_id' => 1,
                'parent_id' => null,
                'name' => 'AI Video Tools',
                'logo' => null,
                'description' => null,
                'tools_count' => 0,
                'status' => 'Active',
                'sort_order' => null,
            ],
            [
                'product_type_id' => 1,
                'parent_id' => 16,
                'name' => 'Video Edition',
                'logo' => null,
                'description' => null,
                'tools_count' => 0,
                'status' => 'Active',
                'sort_order' => null,
            ],
            [
                'product_type_id' => 1,
                'parent_id' => 16,
                'name' => 'Video Generators',
                'logo' => null,
                'description' => null,
                'tools_count' => 0,
                'status' => 'Active',
                'sort_order' => null,
            ],
            [
                'product_type_id' => 1,
                'parent_id' => 16,
                'name' => 'Text-to-video',
                'logo' => null,
                'description' => null,
                'tools_count' => 0,
                'status' => 'Active',
                'sort_order' => null,
            ],
            [
                'product_type_id' => 1,
                'parent_id' => null,
                'name' => 'AI Text Generators',
                'logo' => null,
                'description' => null,
                'tools_count' => 0,
                'status' => 'Active',
                'sort_order' => null,
            ],
            [
                'product_type_id' => 1,
                'parent_id' => 20,
                'name' => 'Storytelling Generator',
                'logo' => null,
                'description' => null,
                'tools_count' => 0,
                'status' => 'Active',
                'sort_order' => null,
            ],
            [
                'product_type_id' => 1,
                'parent_id' => 20,
                'name' => 'Text Generators',
                'logo' => null,
                'description' => null,
                'tools_count' => 0,
                'status' => 'Active',
                'sort_order' => null,
            ],
            [
                'product_type_id' => 1,
                'parent_id' => 20,
                'name' => 'Prompts & Aids',
                'logo' => null,
                'description' => null,
                'tools_count' => 0,
                'status' => 'Active',
                'sort_order' => null,
            ],
            [
                'product_type_id' => 1,
                'parent_id' => 20,
                'name' => 'Writing & Web SEO',
                'logo' => null,
                'description' => null,
                'tools_count' => 0,
                'status' => 'Active',
                'sort_order' => null,
            ],
            [
                'product_type_id' => 1,
                'parent_id' => 20,
                'name' => 'Summarizer',
                'logo' => null,
                'description' => null,
                'tools_count' => 0,
                'status' => 'Active',
                'sort_order' => null,
            ],
            [
                'product_type_id' => 1,
                'parent_id' => null,
                'name' => 'AI Art Generators',
                'logo' => null,
                'description' => null,
                'tools_count' => 0,
                'status' => 'Active',
                'sort_order' => null,
            ],
            [
                'product_type_id' => 1,
                'parent_id' => 26,
                'name' => 'Art',
                'logo' => null,
                'description' => null,
                'tools_count' => 0,
                'status' => 'Active',
                'sort_order' => null,
            ],
            [
                'product_type_id' => 1,
                'parent_id' => 26,
                'name' => 'Avatars',
                'logo' => null,
                'description' => null,
                'tools_count' => 0,
                'status' => 'Active',
                'sort_order' => null,
            ],
            [
                'product_type_id' => 1,
                'parent_id' => 26,
                'name' => 'Logo creation',
                'logo' => null,
                'description' => null,
                'tools_count' => 0,
                'status' => 'Active',
                'sort_order' => null,
            ],
            [
                'product_type_id' => 1,
                'parent_id' => 26,
                'name' => 'Image editing',
                'logo' => null,
                'description' => null,
                'tools_count' => 0,
                'status' => 'Active',
                'sort_order' => null,
            ],
            [
                'product_type_id' => 1,
                'parent_id' => 26,
                'name' => 'Image Generators',
                'logo' => null,
                'description' => null,
                'tools_count' => 0,
                'status' => 'Active',
                'sort_order' => null,
            ],
            [
                'product_type_id' => 1,
                'parent_id' => 26,
                'name' => '3D model',
                'logo' => null,
                'description' => null,
                'tools_count' => 0,
                'status' => 'Active',
                'sort_order' => null,
            ],
            [
                'product_type_id' => 1,
                'parent_id' => null,
                'name' => 'Automation Tools',
                'logo' => null,
                'description' => null,
                'tools_count' => 0,
                'status' => 'Active',
                'sort_order' => null,
            ],
            [
                'product_type_id' => 1,
                'parent_id' => 33,
                'name' => 'AI Agents',
                'logo' => null,
                'description' => null,
                'tools_count' => 0,
                'status' => 'Active',
                'sort_order' => null,
            ],
            [
                'product_type_id' => 1,
                'parent_id' => 33,
                'name' => 'Automation',
                'logo' => null,
                'description' => null,
                'tools_count' => 0,
                'status' => 'Active',
                'sort_order' => null,
            ],
            [
                'product_type_id' => 1,
                'parent_id' => null,
                'name' => 'AI Audio & Music',
                'logo' => null,
                'description' => null,
                'tools_count' => 0,
                'status' => 'Active',
                'sort_order' => null,
            ],
            [
                'product_type_id' => 1,
                'parent_id' => 36,
                'name' => 'Voice Cloning',
                'logo' => null,
                'description' => null,
                'tools_count' => 0,
                'status' => 'Active',
                'sort_order' => null,
            ],
            [
                'product_type_id' => 1,
                'parent_id' => 36,
                'name' => 'Audio Editing',
                'logo' => null,
                'description' => null,
                'tools_count' => 0,
                'status' => 'Active',
                'sort_order' => null,
            ],
            [
                'product_type_id' => 1,
                'parent_id' => 36,
                'name' => 'Text To Speech',
                'logo' => null,
                'description' => null,
                'tools_count' => 0,
                'status' => 'Active',
                'sort_order' => null,
            ],
            [
                'product_type_id' => 1,
                'parent_id' => 36,
                'name' => 'Music',
                'logo' => null,
                'description' => null,
                'tools_count' => 0,
                'status' => 'Active',
                'sort_order' => null,
            ],
            [
                'product_type_id' => 1,
                'parent_id' => 36,
                'name' => 'Transcriber',
                'logo' => null,
                'description' => null,
                'tools_count' => 0,
                'status' => 'Active',
                'sort_order' => null,
            ],
            [
                'product_type_id' => 1,
                'parent_id' => null,
                'name' => 'AI Business Tools',
                'logo' => null,
                'description' => null,
                'tools_count' => 0,
                'status' => 'Active',
                'sort_order' => null,
            ],
            [
                'product_type_id' => 1,
                'parent_id' => 42,
                'name' => 'Business',
                'logo' => null,
                'description' => null,
                'tools_count' => 0,
                'status' => 'Active',
                'sort_order' => null,
            ],
            [
                'product_type_id' => 1,
                'parent_id' => 42,
                'name' => 'E-commerce',
                'logo' => null,
                'description' => null,
                'tools_count' => 0,
                'status' => 'Active',
                'sort_order' => null,
            ],
            [
                'product_type_id' => 1,
                'parent_id' => 42,
                'name' => 'Finance',
                'logo' => null,
                'description' => null,
                'tools_count' => 0,
                'status' => 'Active',
                'sort_order' => null,
            ],
            [
                'product_type_id' => 1,
                'parent_id' => 42,
                'name' => 'Marketing',
                'logo' => null,
                'description' => null,
                'tools_count' => 0,
                'status' => 'Active',
                'sort_order' => null,
            ],
            [
                'product_type_id' => 1,
                'parent_id' => 42,
                'name' => 'Social Networks',
                'logo' => null,
                'description' => null,
                'tools_count' => 0,
                'status' => 'Active',
                'sort_order' => null,
            ],
            [
                'product_type_id' => 1,
                'parent_id' => 42,
                'name' => 'Human Resources',
                'logo' => null,
                'description' => null,
                'tools_count' => 0,
                'status' => 'Active',
                'sort_order' => null,
            ],
            [
                'product_type_id' => 1,
                'parent_id' => 42,
                'name' => 'SEO',
                'logo' => null,
                'description' => null,
                'tools_count' => 0,
                'status' => 'Active',
                'sort_order' => null,
            ],
            [
                'product_type_id' => 1,
                'parent_id' => 42,
                'name' => 'Customer Support',
                'logo' => null,
                'description' => null,
                'tools_count' => 0,
                'status' => 'Active',
                'sort_order' => null,
            ],
            [
                'product_type_id' => 1,
                'parent_id' => 42,
                'name' => 'Sales & Conversion',
                'logo' => null,
                'description' => null,
                'tools_count' => 0,
                'status' => 'Active',
                'sort_order' => null,
            ],
            [
                'product_type_id' => 1,
                'parent_id' => null,
                'name' => 'AI Data & Research',
                'logo' => null,
                'description' => null,
                'tools_count' => 0,
                'status' => 'Active',
                'sort_order' => null,
            ],
            [
                'product_type_id' => 1,
                'parent_id' => 52,
                'name' => 'Data & Analytics',
                'logo' => null,
                'description' => null,
                'tools_count' => 0,
                'status' => 'Active',
                'sort_order' => null,
            ],
            [
                'product_type_id' => 1,
                'parent_id' => 52,
                'name' => 'AI detection',
                'logo' => null,
                'description' => null,
                'tools_count' => 0,
                'status' => 'Active',
                'sort_order' => null,
            ],
            [
                'product_type_id' => 1,
                'parent_id' => 52,
                'name' => 'Research & Science',
                'logo' => null,
                'description' => null,
                'tools_count' => 0,
                'status' => 'Active',
                'sort_order' => null,
            ],
            [
                'product_type_id' => 1,
                'parent_id' => null,
                'name' => 'AI Code Tools',
                'logo' => null,
                'description' => null,
                'tools_count' => 0,
                'status' => 'Active',
                'sort_order' => null,
            ],
            [
                'product_type_id' => 1,
                'parent_id' => 56,
                'name' => 'Assistant Code',
                'logo' => null,
                'description' => null,
                'tools_count' => 0,
                'status' => 'Active',
                'sort_order' => null,
            ],
            [
                'product_type_id' => 1,
                'parent_id' => 56,
                'name' => 'LLM models',
                'logo' => null,
                'description' => null,
                'tools_count' => 0,
                'status' => 'Active',
                'sort_order' => null,
            ],
            [
                'product_type_id' => 1,
                'parent_id' => 56,
                'name' => 'No Code/Low Code',
                'logo' => null,
                'description' => null,
                'tools_count' => 0,
                'status' => 'Active',
                'sort_order' => null,
            ],
            [
                'product_type_id' => 1,
                'parent_id' => 56,
                'name' => 'Developer Tools',
                'logo' => null,
                'description' => null,
                'tools_count' => 0,
                'status' => 'Active',
                'sort_order' => null,
            ],
            [
                'product_type_id' => 1,
                'parent_id' => 56,
                'name' => 'Github Projects',
                'logo' => null,
                'description' => null,
                'tools_count' => 0,
                'status' => 'Active',
                'sort_order' => null,
            ],
            [
                'product_type_id' => 1,
                'parent_id' => 56,
                'name' => 'Websites & Design',
                'logo' => null,
                'description' => null,
                'tools_count' => 0,
                'status' => 'Active',
                'sort_order' => null,
            ],
            [
                'product_type_id' => 1,
                'parent_id' => null,
                'name' => 'AI Industry Tools',
                'logo' => null,
                'description' => null,
                'tools_count' => 0,
                'status' => 'Active',
                'sort_order' => null,
            ],
            [
                'product_type_id' => 1,
                'parent_id' => 63,
                'name' => 'Real Estate / Architect',
                'logo' => null,
                'description' => null,
                'tools_count' => 0,
                'status' => 'Active',
                'sort_order' => null,
            ],
            [
                'product_type_id' => 1,
                'parent_id' => 63,
                'name' => 'Robots and Devices',
                'logo' => null,
                'description' => null,
                'tools_count' => 0,
                'status' => 'Active',
                'sort_order' => null,
            ],
            [
                'product_type_id' => 1,
                'parent_id' => 63,
                'name' => 'Healthcare',
                'logo' => null,
                'description' => null,
                'tools_count' => 0,
                'status' => 'Active',
                'sort_order' => null,
            ],
            [
                'product_type_id' => 1,
                'parent_id' => 63,
                'name' => 'Assistive technology (AT)',
                'logo' => null,
                'description' => null,
                'tools_count' => 0,
                'status' => 'Active',
                'sort_order' => null,
            ],
            [
                'product_type_id' => 1,
                'parent_id' => null,
                'name' => 'AI Entertainment',
                'logo' => null,
                'description' => null,
                'tools_count' => 0,
                'status' => 'Active',
                'sort_order' => null,
            ],
            [
                'product_type_id' => 1,
                'parent_id' => 68,
                'name' => 'Face Swap & DeepFake',
                'logo' => null,
                'description' => null,
                'tools_count' => 0,
                'status' => 'Active',
                'sort_order' => null,
            ],
            [
                'product_type_id' => 1,
                'parent_id' => 68,
                'name' => 'Fashion',
                'logo' => null,
                'description' => null,
                'tools_count' => 0,
                'status' => 'Active',
                'sort_order' => null,
            ],
            [
                'product_type_id' => 1,
                'parent_id' => 68,
                'name' => 'Amazing',
                'logo' => null,
                'description' => null,
                'tools_count' => 0,
                'status' => 'Active',
                'sort_order' => null,
            ],
            [
                'product_type_id' => 1,
                'parent_id' => 68,
                'name' => 'Games',
                'logo' => null,
                'description' => null,
                'tools_count' => 0,
                'status' => 'Active',
                'sort_order' => null,
            ],
            [
                'product_type_id' => 1,
                'parent_id' => 68,
                'name' => 'AI Characters',
                'logo' => null,
                'description' => null,
                'tools_count' => 0,
                'status' => 'Active',
                'sort_order' => null,
            ],
            [
                'product_type_id' => 1,
                'parent_id' => 68,
                'name' => 'Dating & Relationships',
                'logo' => null,
                'description' => null,
                'tools_count' => 0,
                'status' => 'Active',
                'sort_order' => null,
            ],
            [
                'product_type_id' => 1,
                'parent_id' => 68,
                'name' => 'RIP AI',
                'logo' => null,
                'description' => null,
                'tools_count' => 0,
                'status' => 'Active',
                'sort_order' => null,
            ],
            [
                'product_type_id' => 1,
                'parent_id' => 68,
                'name' => 'This*DoesNotExist',
                'logo' => null,
                'description' => null,
                'tools_count' => 0,
                'status' => 'Active',
                'sort_order' => null,
            ],
            [
                'product_type_id' => 1,
                'parent_id' => 68,
                'name' => 'Travel',
                'logo' => null,
                'description' => null,
                'tools_count' => 0,
                'status' => 'Active',
                'sort_order' => null,
            ],
            [
                'product_type_id' => 1,
                'parent_id' => null,
                'name' => 'AI Selections',
                'logo' => null,
                'description' => null,
                'tools_count' => 0,
                'status' => 'Active',
                'sort_order' => null,
            ],
            [
                'product_type_id' => 1,
                'parent_id' => 78,
                'name' => 'Future Tools',
                'logo' => null,
                'description' => null,
                'tools_count' => 0,
                'status' => 'Active',
                'sort_order' => null,
            ],
            [
                'product_type_id' => 1,
                'parent_id' => 78,
                'name' => 'SuperTools',
                'logo' => null,
                'description' => null,
                'tools_count' => 0,
                'status' => 'Active',
                'sort_order' => null,
            ],
            [
                'product_type_id' => 1,
                'parent_id' => 78,
                'name' => 'AI Useful',
                'logo' => null,
                'description' => null,
                'tools_count' => 0,
                'status' => 'Active',
                'sort_order' => null,
            ],
            [
                'product_type_id' => 1,
                'parent_id' => 78,
                'name' => 'Latest AI',
                'logo' => null,
                'description' => null,
                'tools_count' => 0,
                'status' => 'Active',
                'sort_order' => null,
            ],
            [
                'product_type_id' => 1,
                'parent_id' => 78,
                'name' => 'AlphaTools Selection',
                'logo' => null,
                'description' => null,
                'tools_count' => 0,
                'status' => 'Active',
                'sort_order' => null,
            ],
            [
                'product_type_id' => 1,
                'parent_id' => null,
                'name' => 'Extras',
                'logo' => null,
                'description' => null,
                'tools_count' => 0,
                'status' => 'Active',
                'sort_order' => null,
            ],
            [
                'product_type_id' => 1,
                'parent_id' => 84,
                'name' => 'GPTs List',
                'logo' => null,
                'description' => null,
                'tools_count' => 0,
                'status' => 'Active',
                'sort_order' => null,
            ],
            [
                'product_type_id' => 1,
                'parent_id' => 84,
                'name' => 'Hubspot AI Tools',
                'logo' => null,
                'description' => null,
                'tools_count' => 0,
                'status' => 'Active',
                'sort_order' => null,
            ],
            [
                'product_type_id' => 1,
                'parent_id' => 84,
                'name' => 'Top 100 AI',
                'logo' => null,
                'description' => null,
                'tools_count' => 0,
                'status' => 'Active',
                'sort_order' => null,
            ],
            [
                'product_type_id' => 1,
                'parent_id' => 84,
                'name' => 'Best AI Discord Servers',
                'logo' => null,
                'description' => null,
                'tools_count' => 0,
                'status' => 'Active',
                'sort_order' => null,
            ],
            [
                'product_type_id' => 1,
                'parent_id' => 84,
                'name' => 'Best MCP Servers',
                'logo' => null,
                'description' => null,
                'tools_count' => 0,
                'status' => 'Active',
                'sort_order' => null,
            ],
            [
                'product_type_id' => 1,
                'parent_id' => 84,
                'name' => 'Best AI Girlfriend',
                'logo' => null,
                'description' => null,
                'tools_count' => 0,
                'status' => 'Active',
                'sort_order' => null,
            ],
        ];

        foreach ($data as $item) {
            Category::create($item);
        }
    }
}
