<?php

namespace Database\Seeders;

use App\Models\State;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class StateSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $truncateSql = "TRUNCATE table states";
        DB::connection()->getPdo()->exec($truncateSql);
        $states = [
            
                [
                    "id" => 1,
                    "name" => "New York",
                    "country_id" => 1,
                    "country_code" => "US",
                    "country_name" => "United States",
                    "state_code" => "NY",
                    "created_at" => now(),
                    "updated_at" => now(),
                ],
                [
                    "id" => 2,
                    "name" => "Illinois",
                    "country_id" => 1,
                    "country_code" => "US",
                    "country_name" => "United States",
                    "state_code" => "CA",
                    "created_at" => now(),
                    "updated_at" => now(),
                ],
                [
                    "id" => 3,
                    "name" => "Florida",
                    "country_id" => 1,
                    "country_code" => "US",
                    "country_name" => "United States",
                    "state_code" => "FL",
                    "created_at" => now(),
                    "updated_at" => now(),
                ],
                [
                    "id" => 4,
                    "name" => "Texas",
                    "country_id" => 1,
                    "country_code" => "US",
                    "country_name" => "United States",
                    "state_code" => "TX",
                    "created_at" => now(),
                    "updated_at" => now(),
                ],
                [
                    "id" => 5,
                    "name" => "Pennsylvania",
                    "country_id" => 1,
                    "country_code" => "US",
                    "country_name" => "United States",
                    "state_code" => "PA",
                    "created_at" => now(),
                    "updated_at" => now(),
                ],
                [
                    "id" => 6,
                    "name" => "Georgia",
                    "country_id" => 1,
                    "country_code" => "US",
                    "country_name" => "United States",
                    "state_code" => "GA",
                    "created_at" => now(),
                    "updated_at" => now(),
                ],
                [
                    "id" => 7,
                    "name" => "District of Columbia",
                    "country_id" => 1,
                    "country_code" => "US",
                    "country_name" => "United States",
                    "state_code" => "DC",
                    "created_at" => now(),
                    "updated_at" => now(),
                ],
                [
                    "id" => 8,
                    "name" => "Massachusetts",
                    "country_id" => 1,
                    "country_code" => "US",
                    "country_name" => "United States",
                    "state_code" => "MA",
                    "created_at" => now(),
                    "updated_at" => now(),
                ],
                [
                    "id" => 9,
                    "name" => "Arizona",
                    "country_id" => 1,
                    "country_code" => "US",
                    "country_name" => "United States",
                    "state_code" => "AZ",
                    "created_at" => now(),
                    "updated_at" => now(),
                ],
                [
                    "id" => 10,
                    "name" => "Michigan",
                    "country_id" => 1,
                    "country_code" => "US",
                    "country_name" => "United States",
                    "state_code" => "MI",
                    "created_at" => now(),
                    "updated_at" => now(),
                ],
                [
                    "id" => 11,
                    "name" => "Washington",
                    "country_id" => 1,
                    "country_code" => "US",
                    "country_name" => "United States",
                    "state_code" => "WA",
                    "created_at" => now(),
                    "updated_at" => now(),
                ],
                [
                    "id" => 12,
                    "name" => "Minnesota",
                    "country_id" => 1,
                    "country_code" => "US",
                    "country_name" => "United States",
                    "state_code" => "MN",
                    "created_at" => now(),
                    "updated_at" => now(),
                ],
                [
                    "id" => 13,
                    "name" => "Colorado",
                    "country_id" => 1,
                    "country_code" => "US",
                    "country_name" => "United States",
                    "state_code" => "CO",
                    "created_at" => now(),
                    "updated_at" => now(),
                ],
                [
                    "id" => 14,
                    "name" => "Maryland",
                    "country_id" => 1,
                    "country_code" => "US",
                    "country_name" => "United States",
                    "state_code" => "MD",
                    "created_at" => now(),
                    "updated_at" => now(),
                ],
                [
                    "id" => 15,
                    "name" => "Nevada",
                    "country_id" => 1,
                    "country_code" => "US",
                    "country_name" => "United States",
                    "state_code" => "NV",
                    "created_at" => now(),
                    "updated_at" => now(),
                ],
                [
                    "id" => 16,
                    "name" => "Missouri",
                    "country_id" => 1,
                    "country_code" => "US",
                    "country_name" => "United States",
                    "state_code" => "MO",
                    "created_at" => now(),
                    "updated_at" => now(),
                ],
                [
                    "id" => 17,
                    "name" => "Oregon",
                    "country_id" => 1,
                    "country_code" => "US",
                    "country_name" => "United States",
                    "state_code" => "OR",
                    "created_at" => now(),
                    "updated_at" => now(),
                ],
                [
                    "id" => 18,
                    "name" => "Ohio",
                    "country_id" => 1,
                    "country_code" => "US",
                    "country_name" => "United States",
                    "state_code" => "OH",
                    "created_at" => now(),
                    "updated_at" => now(),
                ],
                [
                    "id" => 19,
                    "name" => "Indiana",
                    "country_id" => 1,
                    "country_code" => "US",
                    "country_name" => "United States",
                    "state_code" => "IN",
                    "created_at" => now(),
                    "updated_at" => now(),
                ],
                [
                    "id" => 20,
                    "name" => "North Carolina",
                    "country_id" => 1,
                    "country_code" => "US",
                    "country_name" => "United States",
                    "state_code" => "NC",
                    "created_at" => now(),
                    "updated_at" => now(),
                ],
                [
                    "id" => 21,
                    "name" => "Virginia",
                    "country_id" => 1,
                    "country_code" => "US",
                    "country_name" => "United States",
                    "state_code" => "VA",
                    "created_at" => now(),
                    "updated_at" => now(),
                ],
                [
                    "id" => 22,
                    "name" => "Wisconsin",
                    "country_id" => 1,
                    "country_code" => "US",
                    "country_name" => "United States",
                    "state_code" => "WI",
                    "created_at" => now(),
                    "updated_at" => now(),
                ],
                [
                    "id" => 23,
                    "name" => "Rhode Island",
                    "country_id" => 1,
                    "country_code" => "US",
                    "country_name" => "United States",
                    "state_code" => "RI",
                    "created_at" => now(),
                    "updated_at" => now(),
                ],
                [
                    "id" => 24,
                    "name" => "Utah",
                    "country_id" => 1,
                    "country_code" => "US",
                    "country_name" => "United States",
                    "state_code" => "UT",
                    "created_at" => now(),
                    "updated_at" => now(),
                ],
                [
                    "id" => 25,
                    "name" => "Tennessee",
                    "country_id" => 1,
                    "country_code" => "US",
                    "country_name" => "United States",
                    "state_code" => "TN",
                    "created_at" => now(),
                    "updated_at" => now(),
                ],
                [
                    "id" => 26,
                    "name" => "Kentucky",
                    "country_id" => 1,
                    "country_code" => "US",
                    "country_name" => "United States",
                    "state_code" => "KY",
                    "created_at" => now(),
                    "updated_at" => now(),
                ],
                [
                    "id" => 27,
                    "name" => "Oklahoma",
                    "country_id" => 1,
                    "country_code" => "US",
                    "country_name" => "United States",
                    "state_code" => "OK",
                    "created_at" => now(),
                    "updated_at" => now(),
                ],
                [
                    "id" => 28,
                    "name" => "Connecticut",
                    "country_id" => 1,
                    "country_code" => "US",
                    "country_name" => "United States",
                    "state_code" => "CT",
                    "created_at" => now(),
                    "updated_at" => now(),
                ],
                [
                    "id" => 29,
                    "name" => "Louisiana",
                    "country_id" => 1,
                    "country_code" => "US",
                    "country_name" => "United States",
                    "state_code" => "LA",
                    "created_at" => now(),
                    "updated_at" => now(),
                ],
                [
                    "id" => 30,
                    "name" => "Hawaii",
                    "country_id" => 1,
                    "country_code" => "US",
                    "country_name" => "United States",
                    "state_code" => "HI",
                    "created_at" => now(),
                    "updated_at" => now(),
                ],
                [
                    "id" => 31,
                    "name" => "Nebraska",
                    "country_id" => 1,
                    "country_code" => "US",
                    "country_name" => "United States",
                    "state_code" => "NE",
                    "created_at" => now(),
                    "updated_at" => now(),
                ],
                [
                    "id" => 32,
                    "name" => "New Mexico",
                    "country_id" => 1,
                    "country_code" => "US",
                    "country_name" => "United States",
                    "state_code" => "NM",
                    "created_at" => now(),
                    "updated_at" => now(),
                ],
                [
                    "id" => 33,
                    "name" => "Alabama",
                    "country_id" => 1,
                    "country_code" => "US",
                    "country_name" => "United States",
                    "state_code" => "AL",
                    "created_at" => now(),
                    "updated_at" => now(),
                ],
                [
                    "id" => 34,
                    "name" => "South Carolina",
                    "country_id" => 1,
                    "country_code" => "US",
                    "country_name" => "United States",
                    "state_code" => "SC",
                    "created_at" => now(),
                    "updated_at" => now(),
                ],
                [
                    "id" => 35,
                    "name" => "Iowa",
                    "country_id" => 1,
                    "country_code" => "US",
                    "country_name" => "United States",
                    "state_code" => "IA",
                    "created_at" => now(),
                    "updated_at" => now(),
                ],
                [
                    "id" => 36,
                    "name" => "Kansas",
                    "country_id" => 1,
                    "country_code" => "US",
                    "country_name" => "United States",
                    "state_code" => "KS",
                    "created_at" => now(),
                    "updated_at" => now(),
                ],
                [
                    "id" => 37,
                    "name" => "Arkansas",
                    "country_id" => 1,
                    "country_code" => "US",
                    "country_name" => "United States",
                    "state_code" => "AR",
                    "created_at" => now(),
                    "updated_at" => now(),
                ],
                [
                    "id" => 38,
                    "name" => "Idaho",
                    "country_id" => 1,
                    "country_code" => "US",
                    "country_name" => "United States",
                    "state_code" => "ID",
                    "created_at" => now(),
                    "updated_at" => now(),
                ],
                [
                    "id" => 39,
                    "name" => "Mississippi",
                    "country_id" => 1,
                    "country_code" => "US",
                    "country_name" => "United States",
                    "state_code" => "MS",
                    "created_at" => now(),
                    "updated_at" => now(),
                ],
                [
                    "id" => 40,
                    "name" => "New Jersey",
                    "country_id" => 1,
                    "country_code" => "US",
                    "country_name" => "United States",
                    "state_code" => "NJ",
                    "created_at" => now(),
                    "updated_at" => now(),
                ],
                [
                    "id" => 41,
                    "name" => "Alaska",
                    "country_id" => 1,
                    "country_code" => "US",
                    "country_name" => "United States",
                    "state_code" => "AK",
                    "created_at" => now(),
                    "updated_at" => now(),
                ],
                [
                    "id" => 42,
                    "name" => "New Hampshire",
                    "country_id" => 1,
                    "country_code" => "US",
                    "country_name" => "United States",
                    "state_code" => "NH",
                    "created_at" => now(),
                    "updated_at" => now(),
                ],
                [
                    "id" => 43,
                    "name" => "North Dakota",
                    "country_id" => 1,
                    "country_code" => "US",
                    "country_name" => "United States",
                    "state_code" => "ND",
                    "created_at" => now(),
                    "updated_at" => now(),
                ],
                [
                    "id" => 44,
                    "name" => "South Dakota",
                    "country_id" => 1,
                    "country_code" => "US",
                    "country_name" => "United States",
                    "state_code" => "SD",
                    "created_at" => now(),
                    "updated_at" => now(),
                ],
                [
                    "id" => 45,
                    "name" => "Montana",
                    "country_id" => 1,
                    "country_code" => "US",
                    "country_name" => "United States",
                    "state_code" => "MT",
                    "created_at" => now(),
                    "updated_at" => now(),
                ],
                [
                    "id" => 46,
                    "name" => "California",
                    "country_id" => 1,
                    "country_code" => "US",
                    "country_name" => "United States",
                    "state_code" => "CA",
                    "created_at" => now(),
                    "updated_at" => now(),
                ],
                [
                    "id" => 47,
                    "name" => "Maine",
                    "country_id" => 1,
                    "country_code" => "US",
                    "country_name" => "United States",
                    "state_code" => "ME",
                    "created_at" => now(),
                    "updated_at" => now(),
                ],
                [
                    "id" => 48,
                    "name" => "Vermont",
                    "country_id" => 1,
                    "country_code" => "US",
                    "country_name" => "United States",
                    "state_code" => "VT",
                    "created_at" => now(),
                    "updated_at" => now(),
                ],
                [
                    "id" => 49,
                    "name" => "West Virginia",
                    "country_id" => 1,
                    "country_code" => "US",
                    "country_name" => "United States",
                    "state_code" => "WV",
                    "created_at" => now(),
                    "updated_at" => now(),
                ],
                [
                    "id" => 50,
                    "name" => "Wyoming",
                    "country_id" => 1,
                    "country_code" => "US",
                    "country_name" => "United States",
                    "state_code" => "WY",
                    "created_at" => now(),
                    "updated_at" => now(),
                ],
        ];

        foreach ($states as $state) {
            State::create($state);
        }
    }
}